apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-ztpspoketwo-sriov-network
  namespace: ztpspoketwo-subscription
spec:
  clusterSelector:
    matchExpressions:
      - {key: name, operator: In, values: ["ztpspoketwo-cluster"]}
